version: '3'
services:
  decision_maker_ui:
    restart: 'always'
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./../.env
    environment:
      - API_URL=http://localhost:8001
